In [12]:
from azureml.core import Workspace, Dataset, Datastore

# اتصال به Workspace
subscription_id = 'f8c5aac3-29fc-4387-858a-1f61722fb57a'
resource_group = 'forskerpl-n0ybkr-rg'
workspace_name = 'forskerpl-n0ybkr-mlw'

ws = Workspace(subscription_id=subscription_id,
               resource_group=resource_group,
               workspace_name=workspace_name)

# گرفتن datastore
datastore = Datastore.get(ws, "researcher_data")

# خواندن همه فایل‌های parquet در مسیر مشخص
dataset = Dataset.Tabular.from_parquet_files(
    path=[(datastore, 'Zahra/012026/Data/MEDS_MDPS/data/train/*.parquet')]    #     Zahra/Data-07-2025/MDP/MEDS_811/data/train
)

# تبدیل به pandas DataFrame
df = dataset.to_pandas_dataframe()
df.head(15)

{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe'}
{'infer_column_types': 'False', 'activity': 'to_pandas_dataframe', 'activityApp': 'TabularDataset'}

    subject_id                time            code  numeric_value
0           51                 NaT  GENDER//Kvinde            NaN
1           51 1991-04-09 00:00:00             DOB            NaN
2           51 2018-05-29 00:00:00         D/DJ039            NaN
3           51 2020-02-19 10:57:00        P/UXUD10            NaN
4           51 2020-02-20 00:00:00         D/DK802            NaN
5           51 2020-02-24 08:25:00         P/AAF20            NaN
6           51 2020-02-24 08:25:00        P/ZZ0150            NaN
7          110                 NaT    GENDER//Mand            NaN
8          110 1953-01-26 00:00:00             DOB            NaN
9          110 2016-05-31 08:08:00        P/UXCD60            NaN
10         110 2016-06-06 00:00:00         D/DN189            NaN
11         110 2016-06-29 00:00:00        D/DM171B            NaN
12         110 2016-06-29 00:00:00        D/DZ966B            NaN
13         110 2016-06-29 11:15:00        P/ZZ0151            NaN
14         110 2016-07-01 09:00:00        P/ZZ0151            NaN

In [13]:
len(df)

448503648

In [14]:
import pandas as pd

# فرض بر این که فایل CSV رو داری
# df = pd.read_csv("your_file.csv")  # یا مستقیم اگر DataFrame آماده‌ست، نیازی نیست

# دسته‌بندی هر subject_id بر اساس وجود کدهای مختلف
m_patients = df[df['code'].str.startswith('M/', na=False)]['subject_id'].unique()
p_patients = df[df['code'].str.startswith('P/', na=False)]['subject_id'].unique()
d_patients = df[df['code'].str.startswith('D/', na=False)]['subject_id'].unique()
s_patients = df[df['code'].str.startswith('S/', na=False)]['subject_id'].unique()

# کل بیماران منحصربه‌فرد
all_patients = df['subject_id'].unique()

# نمایش آمار
print(f"تعداد کل بیماران: {len(all_patients)}")
print(f"تعداد بیمارانی که کد M دارند: {len(m_patients)}")
print(f"تعداد بیمارانی که کد P دارند: {len(p_patients)}")
print(f"تعداد بیمارانی که کد D دارند: {len(d_patients)}")
print(f"تعداد بیمارانی که کد S دارند: {len(s_patients)}")

In [4]:
num_S = df[df['code'].str.startswith('M/', na=False)]
num_S

           subject_id                time       code  numeric_value
17                110 2016-08-15 08:30:00  M/M01AH01            NaN
18                110 2016-08-15 08:30:00  M/N02BE01            NaN
23                110 2016-08-15 11:14:00  M/J01DC02            NaN
24                110 2016-08-15 11:14:00  M/H02AB04            NaN
25                110 2016-08-15 11:14:00  M/B05BB01            NaN
...               ...                 ...        ...            ...
446586523     2218016 2022-03-23 21:50:00  M/H01BB02            NaN
446586525     2218016 2022-03-23 22:26:00  M/H01BB02            NaN
446586527     2218016 2022-03-23 22:45:00  M/H01BB02            NaN
446586528     2218016 2022-03-23 22:55:00  M/H01BB02            NaN
446586529     2218016 2022-03-23 23:45:00  M/H01BB02            NaN

[280865103 rows x 4 columns]

In [5]:
num_S = df[df['code'].str.startswith('S/', na=False)]
num_S

           subject_id                time             code  numeric_value
27                110 2016-08-15 11:46:00         S/KNGB30            NaN
206               173 2018-12-26 14:59:00         S/KLCH00            NaN
593               175 2019-12-24 16:45:56  S/KNCJ45 KNCJ07            NaN
679               175 2020-12-05 09:36:18         S/KNCJ45            NaN
788               197 2020-10-23 09:01:03         S/KNAG74            NaN
...               ...                 ...              ...            ...
446581379     2217292 2021-10-15 13:42:30         S/KCJE20            NaN
446583302     2217732 2021-07-23 11:02:07         S/KJKA21            NaN
446584059     2217877 2018-02-16 10:16:49         S/KNHK57            NaN
446584482     2217973 2017-06-20 14:01:14        S/KJAH01A            NaN
446584582     2217973 2017-08-30 08:54:43         S/KLAF10            NaN

[613235 rows x 4 columns]

In [6]:
num_D = df[df['code'].str.startswith('D/', na=False)]
num_D

           subject_id       time      code  numeric_value
1                  51 2018-05-29   D/DJ039            NaN
3                  51 2020-02-20   D/DK802            NaN
8                 110 2016-06-06   D/DN189            NaN
9                 110 2016-06-29  D/DM171B            NaN
10                110 2016-06-29  D/DZ966B            NaN
...               ...        ...       ...            ...
446586544     2218025 2019-09-16   D/DN300            NaN
446586546     2218025 2021-01-04   D/DM774            NaN
446586548     2218025 2021-05-12  D/DR238A            NaN
446586552     2218025 2022-02-17   D/DM202            NaN
446586555     2218025 2022-03-15  D/DL508D            NaN

[12718535 rows x 4 columns]

In [7]:
subject_counts = df['subject_id'].value_counts()

In [8]:
subject_counts

921542     82106
698589     63430
2016077    60872
954669     58831
1964088    57149
           ...
1169509        1
471874         1
1428518        1
484192         1
1212859        1
Name: subject_id, Length: 1774422, dtype: int64

In [9]:
p_Num = df[df['code'].str.startswith('P/', na=False)]

In [10]:
p_Num

           subject_id                time      code  numeric_value
2                  51 2020-02-19 10:57:00  P/UXUD10            NaN
4                  51 2020-02-24 08:25:00   P/AAF20            NaN
5                  51 2020-02-24 08:25:00  P/ZZ0150            NaN
7                 110 2016-05-31 08:08:00  P/UXCD60            NaN
11                110 2016-06-29 11:15:00  P/ZZ0151            NaN
...               ...                 ...       ...            ...
446586549     2218025 2021-05-12 09:26:00   P/AAF21            NaN
446586550     2218025 2021-05-12 09:26:00  P/KQBA99            NaN
446586551     2218025 2021-05-12 09:26:00  P/ZZ0150            NaN
446586553     2218025 2022-02-17 09:02:00  P/UXRG50            NaN
446586554     2218025 2022-02-17 09:09:00  P/ZZ0151            NaN

[84395421 rows x 4 columns]

In [11]:
import pandas as pd

# پیدا کردن سطرهایی که فقط codeهای نوع /P دارن
only_p = df[df['code'].str.startswith('P/', na=False)]

# بیماران با فقط /P کد
subject_ids_only_p = only_p['subject_id'].unique()

# حالا بیماران با codeهای غیر از /P
not_p = df[~df['code'].str.startswith('P/', na=False)]
subject_ids_with_non_p = set(not_p['subject_id'].unique())

# حذف بیمارانی که فقط /P دارن
only_p_ids_to_exclude = [sid for sid in subject_ids_only_p if sid not in subject_ids_with_non_p]

print("Number of patients with only porcedure code: ", only_p_ids_to_exclude)

Number of patients with only porcedure code:  []

In [12]:
df_filtered = df[~df['code'].str.startswith('P/', na=False)]

In [13]:
subject_counts_MDS = df_filtered['subject_id'].value_counts()

In [14]:
subject_counts_MDS

921542     77724
698589     61349
2016077    58263
954669     55552
1964088    52244
           ...
426371         1
1516916        1
1844066        1
1461868        1
1751704        1
Name: subject_id, Length: 1774422, dtype: int64

In [15]:
subject_counts_df = subject_counts.reset_index()
subject_counts_df.columns = ['subject_id', 'original_count']

subject_counts_MDS_df = subject_counts_MDS.reset_index()
subject_counts_MDS_df.columns = ['subject_id', 'new_count']

In [16]:
import pandas as pd
comparison_df = pd.merge(subject_counts_df, subject_counts_MDS_df, on='subject_id', how='outer')

In [17]:
comparison_df['difference'] =  comparison_df['original_count'] - comparison_df['new_count']

In [18]:
comparison_df = comparison_df.sort_values(by='difference', ascending=False)

In [19]:
comparison_df

         subject_id  original_count  new_count  difference
5           1291159           56179      49845        6334
20           714050           42991      37664        5327
4           1964088           57149      52244        4905
6901        1887674            4650         64        4586
0            921542           82106      77724        4382
...             ...             ...        ...         ...
1652560     1597462              11         11           0
1652558       40721              11         11           0
1652557      261407              11         11           0
1652553      104479              11         11           0
1774421     1212859               1          1           0

[1774422 rows x 4 columns]

In [20]:
unchanged_count = (comparison_df['difference'] == 0).sum()
print("unchanged_count", unchanged_count)

unchanged_count 72980

In [21]:
comparison_df['abs_diff'] = comparison_df['difference'].abs()
most_changed = comparison_df.sort_values(by='abs_diff', ascending=False)

In [22]:
print(most_changed.head(10))

      subject_id  original_count  new_count  difference  abs_diff
5        1291159           56179      49845        6334      6334
20        714050           42991      37664        5327      5327
4        1964088           57149      52244        4905      4905
6901     1887674            4650         64        4586      4586
0         921542           82106      77724        4382      4382
11       1169555           49087      45012        4075      4075
33          9512           36659      33001        3658      3658
3         954669           58831      55552        3279      3279
50       2170514           31182      27956        3226      3226
6         350138           52619      49405        3214      3214

In [24]:
changed_df = comparison_df[comparison_df['difference'] != 0]
min_new_count = changed_df['new_count'].min()
lowest_new_count_patients = changed_df[changed_df['new_count'] == min_new_count]

In [25]:
lowest_new_count_patients = lowest_new_count_patients.rename(
    columns={
        'original_count': 'MDPS codes',
        'new_count': 'MDS codes'
    }
)

In [26]:
lowest_new_count_patients

         subject_id  MDPS codes  MDS codes  difference  abs_diff
1256563     2148773          32          1          31        31
1278713      356913          30          1          29        29
1297023     1310903          29          1          28        28
1304077     1171957          29          1          28        28
1304032     1019088          29          1          28        28
...             ...         ...        ...         ...       ...
1772044      507866           2          1           1         1
1762312     1328943           2          1           1         1
1756070     2153869           2          1           1         1
1755896      715600           2          1           1         1
1765838      669038           2          1           1         1

[322 rows x 5 columns]

.str.upper() شرط را case-insensitive می‌کند

بل از فیلتر، ستون را به pd.StringDtype() تبدیل می‌کند؛ این کار رفتار .str را پایدار و قابل پیش‌بینی می‌کند (<NA> به‌جای NaN)

In [27]:
# کل بیماران منحصربه‌فرد
all_patients = df_filtered['subject_id'].unique()
all_patients
# نمایش آمار

array([     51,     110,     143, ..., 2217973, 2218016, 2218025])

In [28]:
len(all_patients)

1774422

In [29]:
len(df_filtered)

362191135

In [30]:
import pandas as pd
import numpy as np

# امن‌تر: اگر code نال یا غیررشته‌ای بود اذیت نکنه
df['code'] = df['code'].astype('string')
df_filtered = df[~df['code'].str.upper().str.startswith('P/', na=False)].copy()
print("kept rows MDS:", len(df_filtered), " / total:", len(df))

kept rows MDS: 362191135  / total: 446586556

In [31]:
import pandas as pd
import numpy as np

# اطمینان از نوع‌ها (برای خروجی تمیز و بدون خطا)
df_filtered = df_filtered.copy()
df_filtered['subject_id']    = pd.to_numeric(df_filtered['subject_id'], errors='coerce').astype('Int64')
df_filtered['numeric_value'] = pd.to_numeric(df_filtered['numeric_value'], errors='coerce').astype('float32')
df_filtered['time']          = pd.to_datetime(df_filtered['time'], errors='coerce', utc=False)

# ردیف‌های بدون subject_id را حذف کنیم (نمی‌توان شارد کرد)
df_filtered = df_filtered.dropna(subset=['subject_id']).copy()
df_filtered['subject_id'] = df_filtered['subject_id'].astype('int64')

# ۳۶ شارد: هر بیمار فقط در یک فایل (mod 36)
N_SHARDS = 45
df_filtered['__shard__'] = (df_filtered['subject_id'] % N_SHARDS).astype('int16')

print("rows to write:", len(df_filtered))

rows to write: 362191135

In [32]:
import numpy as np
import os

N_SHARDS = 36   #45 for Whole # 36 when we have split
OUT_DIR = "./_TrainMDPS_withoutP_sharded"
os.makedirs(OUT_DIR, exist_ok=True)

cols_out = ['subject_id', 'time', 'code', 'numeric_value']

# فرض: subject_id قبلاً int64 شده و NaNها حذف شده‌اند (طبق سلول قبلی‌ات)
sid_mod = (df_filtered['subject_id'].to_numpy(dtype=np.int64, copy=False) % N_SHARDS)

written = 0
for k in range(N_SHARDS):
    mask = (sid_mod == k)                 # بدون ستون اضافی، فقط یک آرایهٔ NumPy
    part = df_filtered.loc[mask, cols_out].sort_values(['subject_id','time'])
    # اگر می‌خوای حتماً ۳۶ فایل 0..35 داشته باشی حتی اگه خالی باشن:
    # if part.empty:
    #     part = part.iloc[0:0]  # فایل صفر-سطر با همان ستون‌ها
    part.to_parquet(os.path.join(OUT_DIR, f"{k}.parquet"),
                    engine="pyarrow", compression="snappy", index=False)
    written += 1

print(f"Done. wrote {written} parquet files into {OUT_DIR}")

Done. wrote 36 parquet files into ./_TrainMDPS_withoutP_sharded

In [4]:
import pyarrow.parquet as pq

OUT_DIR = "./_TrainMDPS_withoutP_sharded"

def parquet_num_rows(path):
    pf = pq.ParquetFile(path)
    md = pf.metadata
    return sum(md.row_group(i).num_rows for i in range(md.num_row_groups))

total = 0
for f in sorted(p for p in os.listdir(OUT_DIR) if p.endswith('.parquet')):
    n = parquet_num_rows(os.path.join(OUT_DIR, f))
    total += n
    print(f, "rows:", n)
print("TOTAL rows:", total)

0.parquet rows: 9990253
1.parquet rows: 10098138
10.parquet rows: 9740592
11.parquet rows: 10039693
12.parquet rows: 9922416
13.parquet rows: 10126304
14.parquet rows: 10071647
15.parquet rows: 10026773
16.parquet rows: 9958243
17.parquet rows: 9875405
18.parquet rows: 10134879
19.parquet rows: 10343817
2.parquet rows: 10186017
20.parquet rows: 10047058
21.parquet rows: 10156203
22.parquet rows: 10304623
23.parquet rows: 10133001
24.parquet rows: 9929420
25.parquet rows: 10079937
26.parquet rows: 10151699
27.parquet rows: 9986545
28.parquet rows: 10279372
29.parquet rows: 9848727
3.parquet rows: 9938416
30.parquet rows: 9917690
31.parquet rows: 10084771
32.parquet rows: 10202567
33.parquet rows: 10069348
34.parquet rows: 9805497
35.parquet rows: 10058175
4.parquet rows: 9841296
5.parquet rows: 10356752
6.parquet rows: 10163221
7.parquet rows: 9872449
8.parquet rows: 10260261
9.parquet rows: 10189930
TOTAL rows: 362191135

In [6]:
from azureml.data.datapath import DataPath
from azureml.data.dataset_factory import FileDatasetFactory
import os

OUT_DIR = "./_TrainMDPS_withoutP_sharded"
DST_PREFIX = "Zahra/012026/Data/MEDS_MDS/data/train"  #held_out"  # بدون اسلشِ اول
''

# اطمینان: پوشه خروجی وجود دارد و فایل parquet داخلش هست
print("Local files to upload:", len([f for f in os.listdir(OUT_DIR) if f.endswith(".parquet")]))

# مقصد روی Datastore
target = DataPath(datastore, DST_PREFIX)

# آپلود همه محتویات OUT_DIR به DST_PREFIX
_ = FileDatasetFactory.upload_directory(
    src_dir=OUT_DIR,
    target=target,
    overwrite=True,
    show_progress=True,
)
print(f"Uploaded to datastore path: {DST_PREFIX}")

Local files to upload: 36
Validating arguments.
Arguments validated.
'overwrite' is set to True. Any file already present in the target will be overwritten.
Uploading files from '/mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded' to 'Zahra/012026/Data/MEDS_MDS/data/train'
Copying 38 files with concurrency set to 6
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/.amlignore, file 1 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/.amlignore
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/.amlignore.amltmp, file 2 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/.amlignore.amltmp
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/10.parquet, file 3 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/10.parquet
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/0.parquet, file 4 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/0.parquet
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/1.parquet, file 5 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/1.parquet
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/11.parquet, file 6 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/11.parquet
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/12.parquet, file 7 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/12.parquet
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Copied /mnt/batch/tasks/shared/LS_root/mounts/clusters/zahra/code/Users/zahra.sobhaninia/Corebehrt_OOT/corebehrt/Myconfigs/CreateIdenticalData/_TrainMDPS_withoutP_sharded/13.parquet, file 8 out of 38. Destination path: https://forskerpln0ybkrdls01.dfs.core.windows.net/researcher-data/Zahra/012026/Data/MEDS_MDS/data/train/13.parquet
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".

In [8]:
paths = Dataset.File.from_files(path=[(datastore, f"{DST_PREFIX}/*.parquet")]).to_path()
print("Found in datastore:", len(paths))
print(paths[:20])

{'infer_column_types': 'False', 'activity': 'to_path'}
{'infer_column_types': 'False', 'activity': 'to_path', 'activityApp': 'FileDataset'}
Resolving access token for scope "https://storage.azure.com/.default" using identity of type "MANAGED".
Getting data access token with Assigned Identity (client_id=clientid) and endpoint type based on configuration
Found in datastore: 36
['/0.parquet', '/1.parquet', '/10.parquet', '/11.parquet', '/12.parquet', '/13.parquet', '/14.parquet', '/15.parquet', '/16.parquet', '/17.parquet', '/18.parquet', '/19.parquet', '/2.parquet', '/20.parquet', '/21.parquet', '/22.parquet', '/23.parquet', '/24.parquet', '/25.parquet', '/26.parquet']